const radicalDetails = {
1: { word: "一点儿", pinyin: "yī diǎnr", meaning: "Một chút", sentence: "我要喝一点儿水。", sentencePy: "Wǒ yào hē yī diǎnr shuǐ.", sentenceVi: "Tôi muốn uống một chút nước." },
2: { word: "中心", pinyin: "zhōng xīn", meaning: "Trung tâm", sentence: "市中心在哪儿？", sentencePy: "Shì zhōngxīn zài nǎr?", sentenceVi: "Trung tâm thành phố ở đâu?" },
3: { word: "丸子", pinyin: "wán zi", meaning: "Viên (thịt, cá)", sentence: "我不吃丸子。", sentencePy: "Wǒ bù chī wánzi.", sentenceVi: "Tôi không ăn thịt viên." },
4: { word: "很久", pinyin: "hěn jiǔ", meaning: "Rất lâu", sentence: "我等了很久。", sentencePy: "Wǒ děng le hěn jiǔ.", sentenceVi: "Tôi đã đợi rất lâu." },
5: { word: "也", pinyin: "yě", meaning: "Cũng", sentence: "我也去北京。", sentencePy: "Wǒ yě qù Běijīng.", sentenceVi: "Tôi cũng đi Bắc Kinh." },
6: { word: "了解", pinyin: "liǎo jiě", meaning: "Hiểu, tìm hiểu", sentence: "我很了解他。", sentencePy: "Wǒ hěn liǎojiě tā.", sentenceVi: "Tôi rất hiểu anh ấy." },
7: { word: "二手", pinyin: "èr shǒu", meaning: "Đồ cũ", sentence: "我买了一辆二手车。", sentencePy: "Wǒ mǎi le yī liàng èrshǒu chē.", sentenceVi: "Tôi đã mua một chiếc xe cũ." },
8: { word: "交通", pinyin: "jiāo tōng", meaning: "Giao thông", sentence: "这里的交通很方便。", sentencePy: "Zhèlǐ de jiāotōng hěn fāngbiàn.", sentenceVi: "Giao thông ở đây rất thuận tiện." },
9: { word: "人口", pinyin: "rén kǒu", meaning: "Dân số", sentence: "中国人口很多。", sentencePy: "Zhōngguó rénkǒu hěn duō.", sentenceVi: "Dân số Trung Quốc rất đông." },
10: { word: "儿子", pinyin: "ér zi", meaning: "Con trai", sentence: "他是我儿子。", sentencePy: "Tā shì wǒ érzi.", sentenceVi: "Cậu ấy là con trai tôi." },
11: { word: "入口", pinyin: "rù kǒu", meaning: "Lối vào", sentence: "入口在前面。", sentencePy: "Rùkǒu zài qiánmiàn.", sentenceVi: "Lối vào ở phía trước." },
12: { word: "八月", pinyin: "bā yuè", meaning: "Tháng Tám", sentence: "我是八月出生的。", sentencePy: "Wǒ shì bā yuè chūshēng de.", sentenceVi: "Tôi sinh vào tháng Tám." },
13: { word: "册子", pinyin: "cè zi", meaning: "Cuốn sổ", sentence: "给我那个小册子。", sentencePy: "Gěi wǒ nà ge xiǎocèzi.", sentenceVi: "Đưa cho tôi cuốn sổ tay kia." },
14: { word: "冠军", pinyin: "guàn jūn", meaning: "Quán quân", sentence: "他是冠军。", sentencePy: "Tā shì guànjūn.", sentenceVi: "Anh ấy là quán quân." },
15: { word: "冰水", pinyin: "bīng shuǐ", meaning: "Nước đá", sentence: "给我一杯冰水。", sentencePy: "Gěi wǒ yī bēi bīngshuǐ.", sentenceVi: "Cho tôi một ly nước đá." },
16: { word: "几个", pinyin: "jǐ ge", meaning: "Mấy cái", sentence: "你要买几个？", sentencePy: "Nǐ yào mǎi jǐ ge?", sentenceVi: "Bạn muốn mua mấy cái?" },
17: { word: "凶手", pinyin: "xiōng shǒu", meaning: "Hung thủ", sentence: "找到凶手了没？", sentencePy: "Zhǎodào xiōngshǒu le méi?", sentenceVi: "Đã tìm thấy hung thủ chưa?" },
18: { word: "刀子", pinyin: "dāo zi", meaning: "Con dao", sentence: "这把刀子很锋利。", sentencePy: "Zhè bǎ dāozi hěn fēnglì.", sentenceVi: "Con dao này rất sắc." },
19: { word: "努力", pinyin: "nǔ lì", meaning: "Nỗ lực", sentence: "他工作很努力。", sentencePy: "Tā gōngzuò hěn nǔlì.", sentenceVi: "Anh ấy làm việc rất cố gắng." },
20: { word: "勺子", pinyin: "sháo zi", meaning: "Cái thìa", sentence: "我不吃勺子里的饭。", sentencePy: "Wǒ bù chī sháozi lǐ de fàn.", sentenceVi: "Tôi không ăn cơm trong thìa." },
21: { word: "北京", pinyin: "Běi jīng", meaning: "Bắc Kinh", sentence: "我去过北京。", sentencePy: "Wǒ qù guo Běijīng.", sentenceVi: "Tôi đã từng đến Bắc Kinh." },
22: { word: "工匠", pinyin: "gōng jiàng", meaning: "Thợ thủ công", sentence: "他是一个好工匠。", sentencePy: "Tā shì yí ge hǎo gōngjiàng.", sentenceVi: "Anh ấy là một người thợ tốt." },
23: { word: "匹配", pinyin: "pǐ pèi", meaning: "Phù hợp", sentence: "颜色不匹配。", sentencePy: "Yánsè bù pǐpèi.", sentenceVi: "Màu sắc không tương xứng." },
24: { word: "十足", pinyin: "shí zú", meaning: "Đầy đủ", sentence: "他信心十足。", sentencePy: "Tā xìnxīn shízú.", sentenceVi: "Anh ấy tràn đầy tự tin." },
25: { word: "卡片", pinyin: "kǎ piàn", meaning: "Thẻ", sentence: "这是一张红色的卡片。", sentencePy: "Zhè shì yī zhāng hóngsè de kǎpiàn.", sentenceVi: "Đây là một tấm thẻ màu đỏ." },
26: { word: "危险", pinyin: "wēi xiǎn", meaning: "Nguy hiểm", sentence: "这里很危险。", sentencePy: "Zhèlǐ hěn wēixiǎn.", sentenceVi: "Ở đây rất nguy hiểm." },
27: { word: "历史", pinyin: "lì shǐ", meaning: "Lịch sử", sentence: "我喜欢中国历史。", sentencePy: "Wǒ xǐhuān Zhōngguó lìshǐ.", sentenceVi: "Tôi thích lịch sử Trung Quốc." },
28: { word: "参加", pinyin: "cān jiā", meaning: "Tham gia", sentence: "我要参加考试。", sentencePy: "Wǒ yào cānjiā kǎoshì.", sentenceVi: "Tôi sẽ tham gia kỳ thi." },
29: { word: "又去", pinyin: "yòu qù", meaning: "Lại đi", sentence: "他又去北京了。", sentencePy: "Tā yòu qù Běijīng le.", sentenceVi: "Anh ấy lại đi Bắc Kinh rồi." },
30: { word: "叫", pinyin: "jiào", meaning: "Gọi", sentence: "你叫什么名字？", sentencePy: "Nǐ jiào shénme míngzi?", sentenceVi: "Bạn tên là gì?" },
31: { word: "回国", pinyin: "huí guó", meaning: "Về nước", sentence: "他明天回国。", sentencePy: "Tā míngtiān huíguó.", sentenceVi: "Ngày mai anh ấy về nước." },
32: { word: "地方", pinyin: "dì fang", meaning: "Địa điểm, nơi", sentence: "这是一个好地方。", sentencePy: "Zhè shì yí ge hǎo dìfang.", sentenceVi: "Đây là một nơi tốt." },
33: { word: "声音", pinyin: "shēng yīn", meaning: "Âm thanh", sentence: "声音太大了。", sentencePy: "Shēngyīn tài dà le.", sentenceVi: "Âm thanh lớn quá." },
34: { word: "准备", pinyin: "zhǔn bèi", meaning: "Chuẩn bị", sentence: "你准备好了吗？", sentencePy: "Nǐ zhǔnbèi hǎo le ma?", sentenceVi: "Bạn đã chuẩn bị xong chưa?" },
35: { word: "复习", pinyin: "fù xí", meaning: "Ôn tập", sentence: "我们在复习课文。", sentencePy: "Wǒmen zài fùxí kèwén.", sentenceVi: "Chúng tôi đang ôn tập bài khóa." },
36: { word: "多少", pinyin: "duō shao", meaning: "Bao nhiêu", sentence: "多少钱？", sentencePy: "Duōshao qián?", sentenceVi: "Bao nhiêu tiền?" },
37: { word: "大家", pinyin: "dà jiā", meaning: "Mọi người", sentence: "大家好！", sentencePy: "Dàjiā hǎo!", sentenceVi: "Chào mọi người!" },
38: { word: "姐姐", pinyin: "jiě jie", meaning: "Chị gái", sentence: "我没有姐姐。", sentencePy: "Wǒ méiyǒu jiějie.", sentenceVi: "Tôi không có chị gái." },
39: { word: "学生", pinyin: "xué shēng", meaning: "Học sinh", sentence: "我是学生。", sentencePy: "Wǒ shì xuéshēng.", sentenceVi: "Tôi là học sinh." },
40: { word: "家里", pinyin: "jiā lǐ", meaning: "Trong nhà", sentence: "我在家里。", sentencePy: "Wǒ zài jiālǐ.", sentenceVi: "Tôi đang ở nhà." },
41: { word: "导游", pinyin: "dǎo yóu", meaning: "Hướng dẫn viên", sentence: "他是导游。", sentencePy: "Tā shì dǎoyóu.", sentenceVi: "Anh ấy là hướng dẫn viên du lịch." },
42: { word: "很少", pinyin: "hěn shǎo", meaning: "Rất ít", sentence: "我很少看电视。", sentencePy: "Wǒ hěn shǎo kàn diànshì.", sentenceVi: "Tôi rất ít xem tivi." },
43: { word: "就是", pinyin: "jiù shì", meaning: "Chính là", sentence: "我就是小明。", sentencePy: "Wǒ jiù shì Xiǎomíng.", sentenceVi: "Tôi chính là Tiểu Minh." },
44: { word: "展示", pinyin: "zhǎn shì", meaning: "Trưng bày", sentence: "展示你的作品。", sentencePy: "Zhǎnshì nǐ de zuòpǐn.", sentenceVi: "Hãy trưng bày tác phẩm của bạn." },
45: { word: "出发", pinyin: "chū fā", meaning: "Xuất phát", sentence: "我们马上出发。", sentencePy: "Wǒmen mǎshàng chūfā.", sentenceVi: "Chúng ta xuất phát ngay thôi." },
46: { word: "岁月", pinyin: "suì yuè", meaning: "Năm tháng", sentence: "岁月不饶人。", sentencePy: "Suìyuè bù ráorén.", sentenceVi: "Năm tháng không chừa một ai." },
47: { word: "广州", pinyin: "Guǎng zhōu", meaning: "Quảng Châu", sentence: "我要去广州。", sentencePy: "Wǒ yào qù Guǎngzhōu.", sentenceVi: "Tôi muốn đi Quảng Châu." },
48: { word: "工作", pinyin: "gōng zuò", meaning: "Công việc", sentence: "你去哪儿工作？", sentencePy: "Nǐ qù nǎr gōngzuò?", sentenceVi: "Bạn đi đâu làm việc?" },
49: { word: "自己", pinyin: "zì jǐ", meaning: "Bản thân", sentence: "我要做回我自己。", sentencePy: "Wǒ yào zuò huí wǒ zìjǐ.", sentenceVi: "Tôi muốn làm lại chính mình." },
50: { word: "帮忙", pinyin: "bāng máng", meaning: "Giúp đỡ", sentence: "你能帮个忙吗？", sentencePy: "Nǐ néng bāng ge máng ma?", sentenceVi: "Bạn có thể giúp một việc không?" },
51: { word: "平安", pinyin: "píng ān", meaning: "Bình an", sentence: "祝你一路平安。", sentencePy: "Zhù nǐ yílù píng'ān.", sentenceVi: "Chúc bạn thượng lộ bình an." },
52: { word: "幽默", pinyin: "yōu mò", meaning: "Hài hước", sentence: "他很幽默。", sentencePy: "Tā hěn yōumò.", sentenceVi: "Anh ấy rất hài hước." },
53: { word: "商店", pinyin: "shāng diàn", meaning: "Cửa hàng", sentence: "我去商店买东西。", sentencePy: "Wǒ qù shāngdiàn mǎi dōngxi.", sentenceVi: "Tôi đi cửa hàng mua đồ." },
54: { word: "延迟", pinyin: "yán chí", meaning: "Trì hoãn", sentence: "航班延迟了。", sentencePy: "Hángbān yánchí le.", sentenceVi: "Chuyến bay đã bị hoãn." },
55: { word: "弄错", pinyin: "nòng cuò", meaning: "Làm sai", sentence: "你弄错了。", sentencePy: "Nǐ nòng cuò le.", sentenceVi: "Bạn làm sai rồi." },
56: { word: "方式", pinyin: "fāng shì", meaning: "Phương thức", sentence: "我不喜欢这种方式。", sentencePy: "Wǒ bù xǐhuān zhè zhǒng fāngshì.", sentenceVi: "Tôi không thích phương thức này." },
57: { word: "紧张", pinyin: "jǐn zhāng", meaning: "Căng thẳng", sentence: "不要紧张。", sentencePy: "Búyào jǐnzhāng.", sentenceVi: "Đừng căng thẳng." },
58: { word: "下雪", pinyin: "xià xuě", meaning: "Tuyết rơi", sentence: "外面在下雪。", sentencePy: "Wàimiàn zài xiàxuě.", sentenceVi: "Bên ngoài đang có tuyết rơi." },
59: { word: "影响", pinyin: "yǐng xiǎng", meaning: "Ảnh hưởng", sentence: "不要影响他学习。", sentencePy: "Búyào yǐngxiǎng tā xuéxí.", sentenceVi: "Đừng làm ảnh hưởng anh ấy học tập." },
60: { word: "很好", pinyin: "hěn hǎo", meaning: "Rất tốt", sentence: "天气很好。", sentencePy: "Tiānqì hěn hǎo.", sentenceVi: "Thời tiết rất đẹp." },
61: { word: "忘记", pinyin: "wàng jì", meaning: "Quên", sentence: "我忘记了他的名字。", sentencePy: "Wǒ wàngjì le tā de míngzi.", sentenceVi: "Tôi đã quên tên anh ấy." },
62: { word: "或者", pinyin: "huò zhě", meaning: "Hoặc là", sentence: "你喝茶或者咖啡？", sentencePy: "Nǐ hē chá huòzhě kāfēi?", sentenceVi: "Bạn uống trà hay cà phê?" },
63: { word: "房间", pinyin: "fáng jiān", meaning: "Căn phòng", sentence: "这是我的房间。", sentencePy: "Zhè shì wǒ de fángjiān.", sentenceVi: "Đây là phòng của tôi." },
64: { word: "打字", pinyin: "dǎ zì", meaning: "Đánh máy", sentence: "他打字很快。", sentencePy: "Tā dǎzì hěn kuài.", sentenceVi: "Anh ấy đánh máy rất nhanh." },
65: { word: "树枝", pinyin: "shù zhī", meaning: "Cành cây", sentence: "树枝断了。", sentencePy: "Shùzhī duàn le.", sentenceVi: "Cành cây bị gãy rồi." },
66: { word: "故事", pinyin: "gù shi", meaning: "Câu chuyện", sentence: "给我讲一个故事。", sentencePy: "Gěi wǒ jiǎng yí ge gùshi.", sentenceVi: "Kể cho tôi nghe một câu chuyện." },
67: { word: "文化", pinyin: "wén huà", meaning: "Văn hóa", sentence: "我喜欢中国文化。", sentencePy: "Wǒ xǐhuān Zhōngguó wénhuà.", sentenceVi: "Tôi thích văn hóa Trung Quốc." },
68: { word: "饮料", pinyin: "yǐn liào", meaning: "Đồ uống", sentence: "你想喝什么饮料？", sentencePy: "Nǐ xiǎng hē shénme yǐnliào?", sentenceVi: "Bạn muốn uống đồ uống gì?" },
69: { word: "新闻", pinyin: "xīn wén", meaning: "Tin tức", sentence: "我看新闻了。", sentencePy: "Wǒ kàn xīnwén le.", sentenceVi: "Tôi đã xem tin tức rồi." },
70: { word: "旅游", pinyin: "lǚ yóu", meaning: "Du lịch", sentence: "我们去旅游。", sentencePy: "Wǒmen qù lǚyóu.", sentenceVi: "Chúng ta đi du lịch thôi." },
71: { word: "既然", pinyin: "jì rán", meaning: "Đã", sentence: "既然来了，就吃吧。", sentencePy: "Jìrán lái le, jiù chī ba.", sentenceVi: "Đã đến rồi thì ăn thôi." },
72: { word: "明天", pinyin: "míng tiān", meaning: "Ngày mai", sentence: "明天见。", sentencePy: "Míngtiān jiàn.", sentenceVi: "Ngày mai gặp lại." },
73: { word: "歌曲", pinyin: "gē qǔ", meaning: "Bài hát", sentence: "这首歌曲很好听。", sentencePy: "Zhè shǒu gēqǔ hěn hǎotīng.", sentenceVi: "Bài hát này rất hay." },
74: { word: "星期", pinyin: "xīng qī", meaning: "Tuần lễ", sentence: "下个星期见。", sentencePy: "Xià ge xīngqī jiàn.", sentenceVi: "Gặp lại vào tuần sau." },
75: { word: "树木", pinyin: "shù mù", meaning: "Cây cối", sentence: "这里有很多树木。", sentencePy: "Zhèlǐ yǒu hěn duō shùmù.", sentenceVi: "Ở đây có rất nhiều cây." },
76: { word: "喜欢", pinyin: "xǐ huan", meaning: "Thích", sentence: "我喜欢学汉语。", sentencePy: "Wǒ xǐhuan xué Hànyǔ.", sentenceVi: "Tôi thích học tiếng Trung." },
77: { word: "正在", pinyin: "zhèng zài", meaning: "Đang", sentence: "我正在吃饭。", sentencePy: "Wǒ zhèngzài chīfàn.", sentenceVi: "Tôi đang ăn cơm." },
78: { word: "死亡", pinyin: "sǐ wáng", meaning: "Chết chóc", sentence: "车祸导致死亡。", sentencePy: "Chēhuò dǎozhì sǐwáng.", sentenceVi: "Tai nạn xe gây tử vong." },
79: { word: "一段", pinyin: "yí duàn", meaning: "Một đoạn", sentence: "读一段课文。", sentencePy: "Dú yí duàn kèwén.", sentenceVi: "Hãy đọc một đoạn văn." },
80: { word: "每天", pinyin: "měi tiān", meaning: "Mỗi ngày", sentence: "我每天去跑步。", sentencePy: "Wǒ měitiān qù pǎobù.", sentenceVi: "Tôi chạy bộ mỗi ngày." },
81: { word: "比较", pinyin: "bǐ jiào", meaning: "Khá là, so sánh", sentence: "汉语比较难。", sentencePy: "Hànyǔ bǐjiào nán.", sentenceVi: "Tiếng Trung khá khó." },
82: { word: "尾巴", pinyin: "wěi ba", meaning: "Cái đuôi", sentence: "小狗在摇尾巴。", sentencePy: "Xiǎogǒu zài yáo wěiba.", sentenceVi: "Chó con đang vẫy đuôi." },
83: { word: "人民", pinyin: "rén mín", meaning: "Nhân dân", sentence: "为人民服务。", sentencePy: "Wèi rénmín fúwù.", sentenceVi: "Phục vụ nhân dân." },
84: { word: "天气", pinyin: "tiān qì", meaning: "Thời tiết", sentence: "今天天气很好。", sentencePy: "Jīntiān tiānqì hěn hǎo.", sentenceVi: "Thời tiết hôm nay rất tốt." },
85: { word: "过河", pinyin: "guò hé", meaning: "Qua sông", sentence: "大象可以过河。", sentencePy: "Dàxiàng kěyǐ guò hé.", sentenceVi: "Con voi có thể qua sông." },
86: { word: "热情", pinyin: "rè qíng", meaning: "Nhiệt tình", sentence: "他很热情。", sentencePy: "Tā hěn rèqíng.", sentenceVi: "Anh ấy rất nhiệt tình." },
87: { word: "爬山", pinyin: "pá shān", meaning: "Leo núi", sentence: "周末去爬山吧。", sentencePy: "Zhōumò qù páshān ba.", sentenceVi: "Cuối tuần đi leo núi nhé." },
88: { word: "爸爸", pinyin: "bà ba", meaning: "Bố", sentence: "爸爸在看书。", sentencePy: "Bàba zài kànshū.", sentenceVi: "Bố đang đọc sách." },
89: { word: "爽快", pinyin: "shuǎng kuài", meaning: "Sảng khoái", sentence: "他答应得很爽快。", sentencePy: "Tā dāyìng de hěn shuǎngkuài.", sentenceVi: "Anh ấy đồng ý rất dứt khoát." },
90: { word: "状态", pinyin: "zhuàng tài", meaning: "Trạng thái", sentence: "我状态不好。", sentencePy: "Wǒ zhuàngtài bù hǎo.", sentenceVi: "Trạng thái của tôi không tốt." },
91: { word: "名牌", pinyin: "míng pái", meaning: "Hàng hiệu", sentence: "这是一件名牌衣服。", sentencePy: "Zhè shì yí jiàn míngpái yīfu.", sentenceVi: "Đây là chiếc áo hàng hiệu." },
92: { word: "优雅", pinyin: "yōu yǎ", meaning: "Thanh lịch", sentence: "她很优雅。", sentencePy: "Tā hěn yōuyǎ.", sentenceVi: "Cô ấy thật thanh lịch." },
93: { word: "特别", pinyin: "tè bié", meaning: "Đặc biệt", sentence: "他很特别。", sentencePy: "Tā hěn tèbié.", sentenceVi: "Anh ấy rất đặc biệt." },
94: { word: "小狗", pinyin: "xiǎo gǒu", meaning: "Chó con", sentence: "这只小狗很可爱。", sentencePy: "Zhè zhī xiǎogǒu hěn kě'ài.", sentenceVi: "Chú chó con này rất dễ thương." },
95: { word: "率领", pinyin: "shuài lǐng", meaning: "Dẫn đầu", sentence: "他率领军队。", sentencePy: "Tā shuàilǐng jūnduì.", sentenceVi: "Ông ấy dẫn đầu quân đội." },
96: { word: "好玩", pinyin: "hǎo wán", meaning: "Thú vị", sentence: "这个游戏很好玩。", sentencePy: "Zhège yóuxì hěn hǎowán.", sentenceVi: "Trò chơi này rất vui." },
97: { word: "花瓣", pinyin: "huā bàn", meaning: "Cánh hoa", sentence: "花瓣落了。", sentencePy: "Huābàn luò le.", sentenceVi: "Cánh hoa đã rụng." },
98: { word: "陶瓷", pinyin: "táo cí", meaning: "Gốm sứ", sentence: "这是中国陶瓷。", sentencePy: "Zhè shì Zhōngguó táocí.", sentenceVi: "Đây là gốm sứ Trung Quốc." },
99: { word: "甜点", pinyin: "tián diǎn", meaning: "Đồ ngọt", sentence: "我喜欢吃甜点。", sentencePy: "Wǒ xǐhuān chī tiándiǎn.", sentenceVi: "Tôi thích ăn bánh ngọt." },
100: { word: "出差", pinyin: "chū chāi", meaning: "Công tác", sentence: "他明天出差。", sentencePy: "Tā míngtiān chūchāi.", sentenceVi: "Anh ấy đi công tác ngày mai." }
};
module.exports = radicalDetails;
