const radicalDetails2 = {
101: { word: "不用", pinyin: "bú yòng", meaning: "Không cần", sentence: "你不用来了。", sentencePy: "Nǐ búyòng lái le.", sentenceVi: "Bạn không cần đến đâu." },
102: { word: "画画", pinyin: "huà huà", meaning: "Vẽ tranh", sentence: "她喜欢画画。", sentencePy: "Tā xǐhuān huàhuà.", sentenceVi: "Cô ấy thích vẽ tranh." },
103: { word: "怀疑", pinyin: "huái yí", meaning: "Nghi ngờ", sentence: "我怀疑他没来。", sentencePy: "Wǒ huáiyí tā méi lái.", sentenceVi: "Tôi nghi ngờ anh ấy chưa đến." },
104: { word: "生病", pinyin: "shēng bìng", meaning: "Bị ốm", sentence: "她生病了。", sentencePy: "Tā shēngbìng le.", sentenceVi: "Cô ấy bị ốm rồi." },
105: { word: "登山", pinyin: "dēng shān", meaning: "Leo núi", sentence: "我们去登山。", sentencePy: "Wǒmen qù dēngshān.", sentenceVi: "Chúng ta đi leo núi." },
106: { word: "白色", pinyin: "bái sè", meaning: "Màu trắng", sentence: "雪是白色的。", sentencePy: "Xuě shì báisè de.", sentenceVi: "Tuyết màu trắng." },
107: { word: "皮肤", pinyin: "pí fū", meaning: "Da", sentence: "她的皮肤很好。", sentencePy: "Tā de pífū hěn hǎo.", sentenceVi: "Da cô ấy rất đẹp." },
108: { word: "盖章", pinyin: "gài zhāng", meaning: "Đóng dấu", sentence: "请在这里盖章。", sentencePy: "Qǐng zài zhèlǐ gàizhāng.", sentenceVi: "Xin hãy đóng dấu ở đây." },
109: { word: "眼睛", pinyin: "yǎn jing", meaning: "Đôi mắt", sentence: "她的眼睛很大。", sentencePy: "Tā de yǎnjing hěn dà.", sentenceVi: "Mắt cô ấy rất to." },
110: { word: "温柔", pinyin: "wēn róu", meaning: "Dịu dàng", sentence: "他的妻子很温柔。", sentencePy: "Tā de qīzi hěn wēnróu.", sentenceVi: "Vợ anh ấy rất dịu dàng." },
111: { word: "知道", pinyin: "zhī dào", meaning: "Biết", sentence: "我不知道。", sentencePy: "Wǒ bù zhīdào.", sentenceVi: "Tôi không biết." },
112: { word: "破坏", pinyin: "pò huài", meaning: "Phá hoại", sentence: "不要破坏环境。", sentencePy: "Búyào pòhuài huánjìng.", sentenceVi: "Đừng phá hoại môi trường." },
113: { word: "祝福", pinyin: "zhù fú", meaning: "Chúc phúc", sentence: "祝福你们！", sentencePy: "Zhùfú nǐmen!", sentenceVi: "Chúc phúc cho các bạn!" },
114: { word: "离开", pinyin: "lí kāi", meaning: "Rời khỏi", sentence: "他离开家了。", sentencePy: "Tā líkāi jiā le.", sentenceVi: "Anh ấy rời khỏi nhà rồi." },
115: { word: "秋天", pinyin: "qiū tiān", meaning: "Mùa thu", sentence: "秋天到了。", sentencePy: "Qiūtiān dào le.", sentenceVi: "Mùa thu đến rồi." },
116: { word: "突然", pinyin: "tū rán", meaning: "Đột nhiên", sentence: "天突然下雨了。", sentencePy: "Tiān tūrán xiàyǔ le.", sentenceVi: "Trời đột nhiên đổ mưa." },
117: { word: "站住", pinyin: "zhàn zhù", meaning: "Đứng lại", sentence: "你给我站住！", sentencePy: "Nǐ gěi wǒ zhànzhù!", sentenceVi: "Cậu đứng lại cho tôi!" },
118: { word: "写字", pinyin: "xiě zì", meaning: "Viết chữ", sentence: "我在写字。", sentencePy: "Wǒ zài xiězì.", sentenceVi: "Tôi đang viết chữ." },
119: { word: "蛋糕", pinyin: "dàn gāo", meaning: "Bánh kem", sentence: "我买了一个蛋糕。", sentencePy: "Wǒ mǎi le yí ge dàngāo.", sentenceVi: "Tôi mua một chiếc bánh kem." },
120: { word: "练习", pinyin: "liàn xí", meaning: "Luyện tập", sentence: "多练习听力。", sentencePy: "Duō liànxí tīnglì.", sentenceVi: "Luyện tập nghe nhiều vào." },
121: { word: "缺点", pinyin: "quē diǎn", meaning: "Khuyết điểm", sentence: "每个人都有缺点。", sentencePy: "Měi ge rén dōu yǒu quēdiǎn.", sentenceVi: "Ai cũng có khuyết điểm." },
122: { word: "布置", pinyin: "bù zhì", meaning: "Sắp xếp, trang trí", sentence: "布置一下房间。", sentencePy: "Bùzhì yíxià fángjiān.", sentenceVi: "Hãy trang trí lại căn phòng một chút." },
123: { word: "美丽", pinyin: "měi lì", meaning: "Xinh đẹp", sentence: "她很美丽。", sentencePy: "Tā hěn měilì.", sentenceVi: "Cô ấy thật xinh đẹp." },
124: { word: "学习", pinyin: "xué xí", meaning: "Học tập", sentence: "他学习很努力。", sentencePy: "Tā xuéxí hěn nǔlì.", sentenceVi: "Anh ấy học hành rất chăm chỉ." },
125: { word: "老师", pinyin: "lǎo shī", meaning: "Giáo viên", sentence: "他是我的老师。", sentencePy: "Tā shì wǒ de lǎoshī.", sentenceVi: "Thầy ấy là giáo viên của tôi." },
126: { word: "耐心", pinyin: "nài xīn", meaning: "Kiên nhẫn", sentence: "他很有耐心。", sentencePy: "Tā hěn yǒu nàixīn.", sentenceVi: "Anh ấy rất kiên nhẫn." },
127: { word: "耕地", pinyin: "gēng dì", meaning: "Cày ruộng", sentence: "农民在耕地。", sentencePy: "Nóngmín zài gēngdì.", sentenceVi: "Nông dân đang cày ruộng." },
128: { word: "聪明", pinyin: "cōng ming", meaning: "Thông minh", sentence: "这个孩子很聪明。", sentencePy: "Zhège háizi hěn cōngming.", sentenceVi: "Đứa trẻ này rất thông minh." },
129: { word: "严肃", pinyin: "yán sù", meaning: "Nghiêm túc", sentence: "老板很严肃。", sentencePy: "Lǎobǎn hěn yánsù.", sentenceVi: "Ông chủ rất nghiêm khắc." },
130: { word: "胖子", pinyin: "pàng zi", meaning: "Người béo", sentence: "他是个胖子。", sentencePy: "Tā shì ge pàngzi.", sentenceVi: "Anh ấy là một người béo." },
131: { word: "卧室", pinyin: "wò shì", meaning: "Phòng ngủ", sentence: "这是我的卧室。", sentencePy: "Zhè shì wǒ de wòshì.", sentenceVi: "Đây là phòng ngủ của tôi." },
132: { word: "自己", pinyin: "zì jǐ", meaning: "Bản thân", sentence: "我自己去。", sentencePy: "Wǒ zìjǐ qù.", sentenceVi: "Tôi tự đi." },
133: { word: "至少", pinyin: "zhì shǎo", meaning: "Ít nhất", sentence: "我至少等了半天。", sentencePy: "Wǒ zhìshǎo děng le bàntiān.", sentenceVi: "Tôi đã chờ ít nhất nửa ngày." },
134: { word: "舅舅", pinyin: "jiù jiu", meaning: "Cậu (em của mẹ)", sentence: "明天去舅舅家。", sentencePy: "Míngtiān qù jiùjiu jiā.", sentenceVi: "Ngày mai đến nhà cậu." },
135: { word: "甜点", pinyin: "tián diǎn", meaning: "Món tráng miệng", sentence: "我爱吃甜点。", sentencePy: "Wǒ ài chī tiándiǎn.", sentenceVi: "Tôi thích ăn đồ tráng miệng." },
136: { word: "跳舞", pinyin: "tiào wǔ", meaning: "Khiêu vũ", sentence: "请你跳支舞吧。", sentencePy: "Qǐng nǐ tiàozhī wǔ ba.", sentenceVi: "Mời bạn nhảy một điệu nhé." },
137: { word: "一般", pinyin: "yì bān", meaning: "Bình thường", sentence: "我的成绩一般。", sentencePy: "Wǒ de chéngjì yìbān.", sentenceVi: "Thành tích của tôi bình thường." },
138: { word: "艰难", pinyin: "jiān nán", meaning: "Gian nan", sentence: "生活很艰难。", sentencePy: "Shēnghuó hěn jiānnán.", sentenceVi: "Cuộc sống rất gian nan." },
139: { word: "颜色", pinyin: "yán sè", meaning: "Màu sắc", sentence: "你喜欢什么颜色？", sentencePy: "Nǐ xǐhuān shénme yánsè?", sentenceVi: "Bạn thích màu gì?" },
140: { word: "花儿", pinyin: "huār", meaning: "Bông hoa", sentence: "花儿开了。", sentencePy: "Huār kāi le.", sentenceVi: "Hoa nở rồi." },
141: { word: "老虎", pinyin: "lǎo hǔ", meaning: "Con hổ", sentence: "动物园里有老虎。", sentencePy: "Dòngwùyuán lǐ yǒu lǎohǔ.", sentenceVi: "Trong sở thú có con hổ." },
142: { word: "蚂蚁", pinyin: "mǎ yǐ", meaning: "Con kiến", sentence: "地上有很多蚂蚁。", sentencePy: "Dìshàng yǒu hěn duō mǎyǐ.", sentenceVi: "Trên mặt đất có rất nhiều kiến." },
143: { word: "流血", pinyin: "liú xuè", meaning: "Chảy máu", sentence: "我的手流血了。", sentencePy: "Wǒ de shǒu liúxuè le.", sentenceVi: "Tay tôi chảy máu rồi." },
144: { word: "街道", pinyin: "jiē dào", meaning: "Đường phố", sentence: "这条街道很安静。", sentencePy: "Zhè tiáo jiēdào hěn ānjìng.", sentenceVi: "Con phố này rất yên tĩnh." },
145: { word: "衣服", pinyin: "yī fu", meaning: "Quần áo", sentence: "这件衣服很漂亮。", sentencePy: "Zhè jiàn yīfu hěn piàoliang.", sentenceVi: "Bộ quần áo này rất đẹp." },
146: { word: "要求", pinyin: "yāo qiú", meaning: "Yêu cầu", sentence: "这是我的要求。", sentencePy: "Zhè shì wǒ de yāoqiú.", sentenceVi: "Đây là yêu cầu của tôi." },
147: { word: "看见", pinyin: "kàn jiàn", meaning: "Nhìn thấy", sentence: "我看见他了。", sentencePy: "Wǒ kànjiàn tā le.", sentenceVi: "Tôi nhìn thấy anh ấy rồi." },
148: { word: "解决", pinyin: "jiě jué", meaning: "Giải quyết", sentence: "问题解决了吗？", sentencePy: "Wèntí jiějué le ma?", sentenceVi: "Vấn đề đã được giải quyết chưa?" },
149: { word: "说话", pinyin: "shuō huà", meaning: "Nói chuyện", sentence: "他在说话。", sentencePy: "Tā zài shuōhuà.", sentenceVi: "Anh ấy đang nói chuyện." },
150: { word: "山谷", pinyin: "shān gǔ", meaning: "Thung lũng", sentence: "山谷里很冷。", sentencePy: "Shāngǔ lǐ hěn lěng.", sentenceVi: "Trong thung lũng rất lạnh." },
151: { word: "登山", pinyin: "dēng shān", meaning: "Leo núi", sentence: "我喜欢登山。", sentencePy: "Wǒ xǐhuān dēng shān.", sentenceVi: "Tôi thích leo núi." },
152: { word: "大象", pinyin: "dà xiàng", meaning: "Con voi", sentence: "大象的鼻子很长。", sentencePy: "Dàxiàng de bízi hěn cháng.", sentenceVi: "Mũi của voi rất dài." },
153: { word: "海豹", pinyin: "hǎi bào", meaning: "Hải cẩu", sentence: "海豹很可爱。", sentencePy: "Hǎibào hěn kě'ài.", sentenceVi: "Hải cẩu rất dễ thương." },
154: { word: "贵重", pinyin: "guì zhòng", meaning: "Quý giá", sentence: "不要带贵重物品。", sentencePy: "Búyào dài guìzhòng wùpǐn.", sentenceVi: "Đừng mang đồ vật quý giá." },
155: { word: "赤道", pinyin: "chì dào", meaning: "Xích đạo", sentence: "新加坡在赤道附近。", sentencePy: "Xīnjiāpō zài Chìdào fùjìn.", sentenceVi: "Singapore ở gần đường xích đạo." },
156: { word: "起飞", pinyin: "qǐ fēi", meaning: "Cất cánh", sentence: "飞机快起飞了。", sentencePy: "Fēijī kuài qǐfēi le.", sentenceVi: "Máy bay sắp cất cánh rồi." },
157: { word: "跑步", pinyin: "pǎo bù", meaning: "Chạy bộ", sentence: "我每天跑步。", sentencePy: "Wǒ měitiān pǎobù.", sentenceVi: "Tôi chạy bộ mỗi ngày." },
158: { word: "身体", pinyin: "shēn tǐ", meaning: "Cơ thể, sức khỏe", sentence: "你的身体好吗？", sentencePy: "Nǐ de shēntǐ hāo ma?", sentenceVi: "Sức khỏe cậu tốt chứ?" },
159: { word: "汽车", pinyin: "qì chē", meaning: "Ô tô", sentence: "这是一辆汽车。", sentencePy: "Zhè shì yí liàng qìchē.", sentenceVi: "Đây là một chiếc xe hơi." },
160: { word: "辛苦", pinyin: "xīn kǔ", meaning: "Vất vả", sentence: "你辛苦了。", sentencePy: "Nǐ xīnkǔ le.", sentenceVi: "Bạn đã vất vả rồi." },
161: { word: "早晨", pinyin: "zǎo chén", meaning: "Buổi sáng", sentence: "早晨的空气很好。", sentencePy: "Zǎochén de kōngqì hěn hǎo.", sentenceVi: "Không khí buổi sáng rất tốt." },
162: { word: "送给", pinyin: "sòng gěi", meaning: "Tặng cho", sentence: "这是送给你的礼物。", sentencePy: "Zhè shì sòng gěi nǐ de lǐwù.", sentenceVi: "Đây là món quà tặng cho bạn." },
163: { word: "郊外", pinyin: "jiāo wài", meaning: "Ngoại ô", sentence: "我们去郊外游玩。", sentencePy: "Wǒmen qù jiāowài yóuwán.", sentenceVi: "Chúng tôi đi chơi ở vùng ngoại ô." },
164: { word: "喝酒", pinyin: "hē jiǔ", meaning: "Uống rượu", sentence: "不要喝酒。", sentencePy: "Búyào hē jiǔ.", sentenceVi: "Đừng uống rượu nhé." },
165: { word: "解释", pinyin: "jiě shì", meaning: "Giải thích", sentence: "听我解释。", sentencePy: "Tīng wǒ jiěshì.", sentenceVi: "Nghe tôi giải thích đi." },
166: { word: "里面", pinyin: "lǐ miàn", meaning: "Bên trong", sentence: "里面有人吗？", sentencePy: "Lǐmiàn yǒu rén ma?", sentenceVi: "Bên trong có người không?" },
167: { word: "花钱", pinyin: "huā qián", meaning: "Tiêu tiền", sentence: "这个很花钱。", sentencePy: "Zhège hěn huā qián.", sentenceVi: "Cái này tốn tiền lắm." },
168: { word: "长长", pinyin: "cháng cháng", meaning: "Rất dài", sentence: "长长的头发。", sentencePy: "Cháng cháng de tóufa.", sentenceVi: "Mái tóc rất dài." },
169: { word: "问好", pinyin: "wèn hǎo", meaning: "Hỏi thăm", sentence: "代我向你父母问好。", sentencePy: "Dài wǒ xiàng nǐ fùmǔ wènhǎo.", sentenceVi: "Cho tôi gửi lời hỏi thăm bố mẹ bạn." },
170: { word: "医院", pinyin: "yī yuàn", meaning: "Bệnh viện", sentence: "他在医院工作。", sentencePy: "Tā zài yīyuàn gōngzuò.", sentenceVi: "Anh ấy làm việc ở bệnh viện." },
171: { word: "奴隶", pinyin: "nú lì", meaning: "Nô lệ", sentence: "现在没有奴隶了。", sentencePy: "Xiànzài méiyǒu núlì le.", sentenceVi: "Bây giờ không còn nô lệ nữa." },
172: { word: "虽然", pinyin: "suī rán", meaning: "Tuy nhiên, mặc dù", sentence: "虽然很累，但是很开心。", sentencePy: "Suīrán hěn lèi, dànshì hěn kāixīn.", sentenceVi: "Mặc dù rất mệt nhưng rất vui." },
173: { word: "下雨", pinyin: "xià yǔ", meaning: "Trời mưa", sentence: "外面下雨了。", sentencePy: "Wàimiàn xiàyǔ le.", sentenceVi: "Bên ngoài trời mưa rồi." },
174: { word: "安静", pinyin: "ān jìng", meaning: "Yên tĩnh", sentence: "请安静。", sentencePy: "Qǐng ānjìng.", sentenceVi: "Thoải mái im lặng nhé." },
175: { word: "非常", pinyin: "fēi cháng", meaning: "Vô cùng", sentence: "我非常高兴。", sentencePy: "Wǒ fēicháng gāoxìng.", sentenceVi: "Tôi vô cùng vui mừng." },
176: { word: "笑面", pinyin: "xiào miàn", meaning: "Khuôn mặt cười", sentence: "他总是笑面相迎。", sentencePy: "Tā zǒngshì xiàomiàn xiāng yíng.", sentenceVi: "Anh ấy luôn đón tiếp bằng nụ cười." },
177: { word: "鞋子", pinyin: "xié zi", meaning: "Đôi giày", sentence: "这双鞋子很舒服。", sentencePy: "Zhè shuāng xiézi hěn shūfu.", sentenceVi: "Đôi giày này rất thoải mái." },
178: { word: "坚韧", pinyin: "jiān rèn", meaning: "Kiên cường", sentence: "他性格坚韧。", sentencePy: "Tā xìnggé jiānrèn.", sentenceVi: "Tính cách anh ấy rất kiên cường." },
179: { word: "韭菜", pinyin: "jiǔ cài", meaning: "Cây hẹ", sentence: "我喜欢吃韭菜饺子。", sentencePy: "Wǒ xǐhuān chī jiǔcài jiǎozi.", sentenceVi: "Tôi thích ăn há cảo nhân hẹ." },
180: { word: "声音", pinyin: "shēng yīn", meaning: "Âm thanh", sentence: "你的声音很好听。", sentencePy: "Nǐ de shēngyīn hěn hǎotīng.", sentenceVi: "Giọng của bạn rất hay." },
181: { word: "预习", pinyin: "yù xí", meaning: "Chuẩn bị bài", sentence: "大家先预习课文。", sentencePy: "Dàjiā xiān yùxí kèwén.", sentenceVi: "Mọi người hãy chuẩn bị bài trước." },
182: { word: "刮风", pinyin: "guā fēng", meaning: "Gió thổi", sentence: "外面在刮风。", sentencePy: "Wàimiàn zài guāfēng.", sentenceVi: "Bên ngoài gió đang thổi." },
183: { word: "飞机", pinyin: "fēi jī", meaning: "Máy bay", sentence: "我坐飞机去巴黎。", sentencePy: "Wǒ zuò fēijī qù Bālí.", sentenceVi: "Tôi đi máy bay đến Paris." },
184: { word: "吃饭", pinyin: "chī fàn", meaning: "Ăn cơm", sentence: "你吃饭了吗？", sentencePy: "Nǐ chīfàn le ma?", sentenceVi: "Bạn đã ăn cơm chưa?" },
185: { word: "首先", pinyin: "shǒu xiān", meaning: "Đầu tiên", sentence: "首先，我们要感谢大家。", sentencePy: "Shǒuxiān, wǒmen yào gǎnxiè dàjiā.", sentenceVi: "Lời đầu tiên, xin cảm ơn mọi người." },
186: { word: "香水", pinyin: "xiāng shuǐ", meaning: "Nước hoa", sentence: "这瓶香水很香。", sentencePy: "Zhè píng xiāngshuǐ hěn xiāng.", sentenceVi: "Chai nước hoa này rất thơm." },
187: { word: "骑马", pinyin: "qí mǎ", meaning: "Cưỡi ngựa", sentence: "我不会骑马。", sentencePy: "Wǒ bú huì qímǎ.", sentenceVi: "Tôi không biết cưỡi ngựa." },
188: { word: "骨头", pinyin: "gǔ tou", meaning: "Cục xương", sentence: "狗喜欢吃骨头。", sentencePy: "Gǒu xǐhuān chī gǔtou.", sentenceVi: "Chó thích gặm xương." },
189: { word: "敲门", pinyin: "qiāo mén", meaning: "Gõ cửa", sentence: "有人在敲门。", sentencePy: "Yǒurén zài qiāomén.", sentenceVi: "Có người đang gõ cửa." },
190: { word: "头发", pinyin: "tóu fa", meaning: "Mái tóc", sentence: "她有一头长发。", sentencePy: "Tā yǒu yì tóu cháng fà.", sentenceVi: "Cô ấy có mái tóc dài." },
191: { word: "热闹", pinyin: "rè nao", meaning: "Ná nhiệt", sentence: "这里非常热闹。", sentencePy: "Zhèlǐ fēicháng rènao.", sentenceVi: "Ở đây vô cùng náo nhiệt." },
192: { word: "鬯草", pinyin: "chàng cǎo", meaning: "Cỏ đuôi chó", sentence: "鬯是一种香草。", sentencePy: "Chàng shì yì zhǒng xiāngcǎo.", sentenceVi: "Sướng là một loại cỏ thơm." },
193: { word: "融合", pinyin: "róng hé", meaning: "Dung hợp", sentence: "文化互相融合。", sentencePy: "Wénhuà hùxiāng rónghé.", sentenceVi: "Các nền văn hóa dung hợp lẫn nhau." },
194: { word: "魔鬼", pinyin: "mó guǐ", meaning: "Ma quỷ", sentence: "我不怕魔鬼。", sentencePy: "Wǒ bú pà móguǐ.", sentenceVi: "Tôi không sợ ma quỷ." },
195: { word: "新鲜", pinyin: "xīn xiān", meaning: "Tươi mới", sentence: "这些鱼很新鲜。", sentencePy: "Zhèxiē yú hěn xīnxiān.", sentenceVi: "Những con cá này rất tươi." },
196: { word: "小鸟", pinyin: "xiǎo niǎo", meaning: "Chim nhỏ", sentence: "树上有一只小鸟。", sentencePy: "Shù shàng yǒu yì zhī xiǎoniǎo.", sentenceVi: "Trên cây có một chú chim nhỏ." },
197: { word: "咸菜", pinyin: "xián cài", meaning: "Dưa muối", sentence: "这盘咸菜很好吃。", sentencePy: "Zhè pán xiáncài hěn hǎochī.", sentenceVi: "Đĩa dưa muối này rất ngon." },
198: { word: "长颈鹿", pinyin: "cháng jǐng lù", meaning: "Hươu cao cổ", sentence: "动物园里有长颈鹿。", sentencePy: "Dòngwùyuán lǐ yǒu chángjǐnglù.", sentenceVi: "Sở thú có con hươu cao cổ." },
199: { word: "面包", pinyin: "miàn bāo", meaning: "Bánh mì", sentence: "我早上吃面包。", sentencePy: "Wǒ zǎoshang chī miànbāo.", sentenceVi: "Buổi sáng tôi ăn bánh mì." },
200: { word: "麻烦", pinyin: "má fan", meaning: "Phiền phức", sentence: "这件事情很麻烦。", sentencePy: "Zhè jiàn shìqing hěn máfan.", sentenceVi: "Chuyện này cực kì phiền phức." },
201: { word: "黄色", pinyin: "huáng sè", meaning: "Màu vàng", sentence: "我喜欢黄色的衣服。", sentencePy: "Wǒ xǐhuān huángsè de yīfu.", sentenceVi: "Tôi thích chiếc áo màu vàng." },
202: { word: "黎明", pinyin: "lí míng", meaning: "Bình minh", sentence: "黎明时分我们出发。", sentencePy: "Límíng shífēn wǒmen chūfā.", sentenceVi: "Lúc rạng đông chúng ta sẽ xuất phát." },
203: { word: "黑板", pinyin: "hēi bǎn", meaning: "Bảng đen", sentence: "老师在黑板上写字。", sentencePy: "Lǎoshī zài hēibǎn shàng xiězì.", sentenceVi: "Thầy giáo viết phấn lên bảng đen." },
204: { word: "黹", pinyin: "zhǐ", meaning: "May vá", sentence: "她在从事女黹。", sentencePy: "Tā zài cóngshì nǚ zhǐ.", sentenceVi: "Cô ấy đang làm nghề may vá." },
205: { word: "乌龟", pinyin: "wū guī", meaning: "Con rùa", sentence: "乌龟慢吞吞地爬行。", sentencePy: "Wūguī màn tūntūn de páxíng.", sentenceVi: "Rùa bò chầm chậm." },
206: { word: "鼎盛", pinyin: "dǐng shèng", meaning: "Thịnh vượng", sentence: "国家正处于鼎盛时期。", sentencePy: "Guójiā zhèng chǔyú dǐngshèng shíqī.", sentenceVi: "Đất nước đang vào thời kỳ hưng thịnh." },
207: { word: "鼓励", pinyin: "gǔ lì", meaning: "Khuyến khích", sentence: "他一直鼓励我。", sentencePy: "Tā yìzhí gǔlì wǒ.", sentenceVi: "Anh ấy luôn động viên tôi." },
208: { word: "老鼠", pinyin: "lǎo shǔ", meaning: "Con chuột", sentence: "猫爱抓老鼠。", sentencePy: "Māo ài zhuā lǎoshǔ.", sentenceVi: "Mèo thích bắt chuột." },
209: { word: "鼻子", pinyin: "bí zi", meaning: "Cái mũi", sentence: "大象的鼻子很长。", sentencePy: "Dàxiàng de bízi hěn cháng.", sentenceVi: "Mũi của con voi rất dài." },
210: { word: "整齐", pinyin: "zhěng qí", meaning: "Gọn gàng", sentence: "队伍非常整齐。", sentencePy: "Duìwǔ fēicháng zhěngqí.", sentenceVi: "Đội ngũ vô cùng ngay ngắn." },
211: { word: "年龄", pinyin: "nián líng", meaning: "Tuổi tác", sentence: "你是什么年龄的？", sentencePy: "Nǐ shì shénme niánlíng de?", sentenceVi: "Bạn thuộc độ tuổi nào?" },
212: { word: "龙年", pinyin: "lóng nián", meaning: "Năm rồng", sentence: "今年是龙年。", sentencePy: "Jīnnián shì lóngnián.", sentenceVi: "Năm nay là năm Thìn." },
213: { word: "海龟", pinyin: "hǎi guī", meaning: "Rùa biển", sentence: "我们在海滩上看到海龟。", sentencePy: "Wǒmen zài hǎitān shàng kàndào hǎiguī.", sentenceVi: "Chúng tôi nhìn thấy rùa trên bãi biển." },
214: { word: "龠", pinyin: "yuè", meaning: "Sáo cổ", sentence: "龠是古代的一种乐器。", sentencePy: "Yuè shì gǔdài de yī zhǒng yuèqì.", sentenceVi: "Sáo là một loại nhạc cụ thời cổ đại." }
};

module.exports = radicalDetails2;

